apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations: 
     run.googleapis.com/launch-stage: BETA
  labels:
    cloud.googleapis.com/location: @@REGION@@
  name: apigee-envoy
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen1 #or gen2
    spec:
      containers:
      - env:
        - name: DEBUG
          value: DEBUG
        image: us-docker.pkg.dev/@@PROJECT@@/apigee-cloudrun-mcs-bigtable/envoy-adapter:latest
      - env:
        - name: LOG_LEVEL
          value: info
        - name: APIGEE_HOST
          value: "@@APIGEE_HOST@@"
        image: us-docker.pkg.dev/@@PROJECT@@/apigee-cloudrun-mcs-bigtable/envoy-sidecar:latest
        ports:
          - containerPort: 8080